POST http://localhost:8000/auth/login
Content-Type: application/json

{
   "email":"john@example.com", 
   "password":"password123"
}
###
GET http://localhost:8000/notes?query=play
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ZWQ3YWUxNzQ0ZWMzZWE3ZWM2MWFiNCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGluWjBQQnZsRHNha2tNeURIcXFEZ2VDTWc1NFRvYWsyNDJzU05iLkU2b1VkL21HT01yMXh1IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwiX192IjowfSwiaWF0IjoxNzI3NTkxMTQ4LCJleHAiOjE3Mjc2MjcxNDh9.MfsvTnR2ocUBgFhWliaF9MhbB_-1cW6g9x_KrGgqvCE
###
PUT http://localhost:8000/notes/pin-note/66f019b195554c443ba26658
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ZWQ3YWUxNzQ0ZWMzZWE3ZWM2MWFiNCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGluWjBQQnZsRHNha2tNeURIcXFEZ2VDTWc1NFRvYWsyNDJzU05iLkU2b1VkL21HT01yMXh1IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwiX192IjowfSwiaWF0IjoxNzI3MDkyNDIyLCJleHAiOjE3MjcwOTYwMjJ9.jmJbjoS7WzYWMTFRLfv56y2p0gde-sNEaIHKqP_xecY
###
GET http://localhost:8000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ZWQ3YWUxNzQ0ZWMzZWE3ZWM2MWFiNCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGluWjBQQnZsRHNha2tNeURIcXFEZ2VDTWc1NFRvYWsyNDJzU05iLkU2b1VkL21HT01yMXh1IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwiX192IjowfSwiaWF0IjoxNzI3MDk4MDMyLCJleHAiOjE3MjcxMDE2MzJ9.kPMEMcJxPVfetE3QZLUqRnyWJUR7s7rybn7j8IRXUwQ
###
GET http://localhost:8000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ZWQ3YWUxNzQ0ZWMzZWE3ZWM2MWFiNCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGluWjBQQnZsRHNha2tNeURIcXFEZ2VDTWc1NFRvYWsyNDJzU05iLkU2b1VkL21HT01yMXh1IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwiX192IjowfSwiaWF0IjoxNzI3NTkwODY0LCJleHAiOjE3Mjc2MjY4NjR9.sOoD3iQm0HvG4MSTYslbcreph3tf3MP1qstfcBRspKQ
###
GET http://localhost:8000/auth/verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ZWQ3YWUxNzQ0ZWMzZWE3ZWM2MWFiNCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGluWjBQQnZsRHNha2tNeURIcXFEZ2VDTWc1NFRvYWsyNDJzU05iLkU2b1VkL21HT01yMXh1IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yMFQxMzozODo0MS4wNjVaIiwiX192IjowfSwiaWF0IjoxNzI3NTkwODY0LCJleHAiOjE3Mjc2MjY4NjR9.sOoD3iQm0HvG4MSTYslbcreph3tf3MP1qstfcBRspKQ